var myString;
var myNum;
var myBool;
var myVar;
var strArr;
var numArr;
var boolArr;
var strNumTuple;
myNum = 1 + 1;
myString = 'heyyy' + 'kidsss';
myBool = true;
myVar = 5;
strArr = ['hett', 'yoo'];
numArr = [12, 3, 45, 67, 78, 9, 0];
strNumTuple = ['boy', 1];
